events {}

http {
    include /etc/nginx/mime.types;
    sendfile on;
    keepalive_timeout 65;
    client_max_body_size 21m;

    limit_req_zone $binary_remote_addr zone=upload:10m rate=1r/m;
    limit_req_zone $binary_remote_addr zone=general:10m rate=30r/m;

    server {
        listen 80;
        server_name pawatools.codewithme.co.ke;

        location /api/ {
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /api/upload {
            limit_req zone=upload burst=3 nodelay;
            proxy_pass http://api:8000;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
        }

        location / {
            root /usr/share/nginx/html;
            index index.html;
            try_files $uri $uri/ /index.html;
        }
    }
}
